#!/bin/env bash
dir="/usr/bin/ramallahos-rofi-launcher-resources"
stylenum1=75
stylenum2=16
num1="$(expr $(( $RANDOM % $stylenum1 )) + 1 )"
num2="$(expr $(( $RANDOM % $stylenum2 )) + 1 )"
echo $num1 $num2
theme="style-$num1"
file="${dir}/${theme}.rasi"
sed -i -e "s/@import .*/@import \"$num2.rasi\"/g" $file || true
cd $dir
rofi -show drun -theme $file
